server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://phyllipesa.com.br
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rest-with-spring-boot-udm.c1a0464io4km.us-east-2.rds.amazonaws.com:3306/rest_with_spring_boot_udm?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  cache:
    disabled: true
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    user-root-path: true

# Configuração específica do Flyway
flyway:
  enabled: true
  locations: classpath:db.migration